server:
  port: 9000 #网关端口号
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
# 配置Gateway日志等级，输出转发细节信息
#logging:
 # level:
  #  org.springframework.cloud.gateway: debug  
  
spring:
  application:
    name: cloud-gateway  #服务名
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  		   		   #开启从注册中心动态创建路由的功能，利用微服务名进行路由lb://SERVICE-PRODUCER/girl/hello2

      routes:
        - id: rate-limit-demo
          uri: https://www.jianshu.com
          predicates:
            - Path=/p/d2c3b6851e1d
            
        - id: blog
          uri: http://www.163.com
          predicates:
            - Header=tokensss, \d+
            
        - id: payment_route_1              #路由id，随便写，建议配合服务名
        # uri: lb://SERVICE-PRODUCER  #由于要进行负载均衡，所以用服务名（来自下面 服务端操作 YML）
          uri: http://localhost:9100  #由于要进行负载均衡，所以用服务名（来自下面 服务端操作 YML）
          predicates:
             - Path=/girl/**			#断言，路径想匹配的进行路由
          filters:
         #- StripPrefix=1
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 4
              redis-rate-limiter.burstCapacity: 8
              key-resolver: "#{@pathKeyResolver}"
  redis:
    host: 192.168.30.128
    port: 6379