server:
  port: 9100
  servlet:
    context-path: /girl
spring:
  application:
    name: service-producer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。




